spring:
  application:
    name: bankingMsProducts
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    pool:
      max-size: 5
      initial-size: 2

server:
  port: 11102

secret_keys:
  codes:
    jwt: ${JWT_SECRET}
    crypt_key: ${CRYPT_KEY}
